spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ALPR-Integration?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:/liquibase/changelog/changelog-master.yml